# Generated by Django 5.1.1 on 2024-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('dateline', models.DateField()),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
            },
        ),
    ]
