# Generated by Django 5.1.1 on 2024-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
